_commit: 5fc2505
_src_path: gh:mcc-apsis/ecs-repo-template
dvc_ts01_remote_path: /data/rd5/ecs/DVC/wwcs
dvc_ts01_user: maxca
project_description: ''
projectname: what-works-repo
python_version: '3.14'
use_dvc: true
use_vscode: true
