project:
  created_at: '2026-09-25T13:19:33.143465Z'
  evaluation_strategy: dev_val_test
  gold_standard_data_format: generic_csv
  gold_standard_data_path: ../../data/processed/batches/batch_5/annotations.csv
  name: asdf
  pdf_dir: null
